// GENERATED by tool/generate_station_asset_registry.dart — do not edit.
// Sources: .dart_tool/package_config.json, pubspec.lock, and each
// participating package's top-level `grid:` block.
// Regenerate: dart run tool/generate_station_asset_registry.dart

// Transitive imports are intentional: this is resolved output.
// ignore_for_file: depend_on_referenced_packages

library;

import 'package:grid_sdk/grid_sdk.dart';
import 'package:grid_assets/grid_assets.dart' as grid_assets_grid_asset_pack;

/// The complete asset registry generated for this station.
abstract final class GeneratedGridAssetRegistrant {
  /// Every pack in the resolved station closure.
  ///
  /// Built, not `const`: the SDK factory validates duplicate
  /// logical and artifact identity before exposing the registry.
  static final GridAssetRegistry registry = GridAssetRegistry(
    <GridAssetPackDefinition>[
      grid_assets_grid_asset_pack.GridAssetsPack.definition,
    ],
  );
}
